name: culinary-code-test-keycloak

services:
  idp_postgres:
    image: postgres:15.4-alpine
    volumes:
      - idp_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  idp_keycloak:
    image: culinarycode_idp
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=idp_postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
    #command: start-dev
    ports:
      - "8180:8080"
    depends_on:
      - idp_postgres
  
  
volumes:
  idp_data: