name: culinary-code

services:
  idp_postgres:
    image: postgres:15.4-alpine
    volumes:
      - idp_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
        - "5433:5432"

  idp_keycloak:
      image: steffenvochten/culinarycode_idp
      environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
        - KC_DB=postgres
        - KC_DB_URL_HOST=idp_postgres
        - KC_DB_URL_DATABASE=keycloak
        - KC_DB_USERNAME=keycloak
        - KC_DB_PASSWORD=password
      ports:
        - "8180:8080"
      depends_on:
        - idp_postgres
    
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - backend_data:/var/lib/postgresql/data

volumes:
  backend_data:
  idp_data: